language: java
notifications:
  email: false
  slack:
    secure: a7EUKRymx7w4rbyn3JecXvQUFuhbDyj+yKCG3YD5AorAqDmKYvj3Gh2obc1lJITTTBRQqRgyyJaLVYCrl2b/M53O0ddR0/ZcEMzXvj7Cl2YpNnXkJ4yX8VzI0EIQYXNaP6DWAoXVVnW9V9Gc23W0VIjAd2Y3S6/VKRhAnz4z84BdYqiqde1tXCnVtNueJ9Dq/aB0zcAdO37K9QbKJEXFICf+eYekg9bXtPAnNyr1sRR3qa5Dl+oAcUF/FNFCw+V7vNWfhFkEeoNPupcG3Uv5u9cOZcRlwsmOIYPUa6CFXHeHKv22g2l0PJ8swA+C9/TH6htA7JiOmbIO8IUwHLA5PYg+SBenclfbT8Yh5xuBCVBjFRlv8HJXpiqMjxT6n4AzHllLscc/8/TdsG4AAyXVIsCQlMDgfYM14DvvlAdCY0uBOUEWyDVrIBMzmOSdcxF+MNbaawULEBX5BllFaaKL7SX+haoXFsTisAGjGSuCxdESyB+bustq4X1ZSkqPDUygK8mBHzGe7cKsq000N/Et+u6wBpi0bvvEiwvMTomku3L+8O14Oo1bEs5tT6xf73nieTBSd3IwAtisHlmioDp+oM57V5aYl1LNnIvx+fPvtbsA8VmYITjN0w+YEm4UykWZuerHBm16rU9yIS21fXWasf4+ySAGO2kn5kvR3AJ1cb0=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  --settings .travis/settings.xml -Dmaven.javadoc.skip=true -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: v2eSxpER0ckXZ+jcfth8uE+/eDNFWUwzYK07vJ/rYQMZ7Xp8ZqNyQq4fbY6Y2+hMN9eeixJ+1XFzBeww4AhMN02aB33gStFsEAcKDVojdVyF/5fDWu1u6OEMRuPUq2H9KQQS1wE7CGDdlUoQDoXl9V5ugZDngtV2CJrWRrqS+j4GKTd0SfJFLwjQxbSfN8UgQ0Q1SjDcWbb5qBLo3Qjr8PDFceUqWM5//poE9WjFEvZ+trZaSxL9BVw5X6ZR387w5fbXREWo6lAyUJ6viqL3JzG4bQ9zh3aza/mNgS0W+YO9PMp+kRd4GwHTyDZ6EBXTd3SRCihfZ8t2aYeqsiTeG2I6RqwBxW2nxfMYIpAljDo3ojP+zee5LPpljPhYGMHzTXzVkOUqMMo2RnWKlsiqdm4oIrwGB/Q3SroSUykqgr6aAEL80bbPE05vfFHGKQqZiHIMy24rQsj5Ud2VrT23q3/aBlWyzPY0mX0+mlq9b++mtD+zRQlyWgKRRqDf3apEB8y1HQkkddO/QId5GrKYf/0c1+Q+Srssj50QF3HQ0hrduZKfDtBAFu5Zo9fcWVKb7FfoA+6ddn2jU05/aNk48fvxK4Bu/Dmd/qtjtba5+BV34nWHSD8X9tGbDG1xR+LvTL2T0QrLYl7UVyEWXu++KpyfWYOxsW56adUxampbBL4=
  - secure: zsZYioEIoVGAls9xRIu+uOyGJNpD2gdKn48MotlMK+SNHaQjmQwhwa1Ac8vc0NIom8NfVCtirDRA6od7v694HlEPcI5NLa7gUCJFq2n5muQxfAwzlXpqQyX+7Xnp3qSd8TbJyiOsOEbnPSMqlyVwwr4x5DEAGDaPuAytA1t265vcoVMAuz2tFoWBmuaAXy68RSgXcllNhjqRhiAp0dJJmI9qpKMQg+mmv+UKUIOm97yhtrCXfWfJLC3SlE1B47spzll/e59CM/hEdgLeLOS9gwK9IucCtjacoOe/KxIm4+2uvr1ZwnKBmR8fThVqHYNz75FjgzrxId6h6JlHsrNEjvw3pziwLNrLzFUOB+pI3zV2LcanfuzgrVs17NHnjxKvnQT8ftJzMDAjDECccy2tg6u1enbnvME43yjkFnYlokfFn2g+vojqGqFXAB3MIAHfStteVrXM6E147inM+wcTL67RpkAiCKqdl0fepvCY2/ZXTVg250zN2d/WvMloolpZoC81svbeKjmuwriWUzw9IWRaR+5jxup3+IPeKFSOFGVY8fdT2lYwk+MmPr/Rrgh/v0lOkqBvS5cpYGVtBrIQOkOT2c3nAxAgG2V9sjqMBSvvFYjHhUnhQgEZCfC7+HKNKWSjvF3lyh2XmYXsTlmCnZujD3HlO1TWtvNqjo+Vj4c=
